apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-local
        imagePullPolicy: Never
        livenessProbe:
            exec:
              command:
                - /bin/sh
                - /probe.sh
            initialDelaySeconds: 10
            periodSeconds: 5
        ports:
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
  type: LoadBalancer